# TreeScribe Configuration File
title = "TreeScribe Parser Configuration"
version = "2.0.0"

[application]
name = "TreeScribe"
description = """
A universal document parser that can handle multiple formats
with a unified tree-based interface."""
homepage = "https://treescribe.dev"
authors = ["TreeScribe Team <team@treescribe.dev>"]

[server]
host = "0.0.0.0"
port = 3600
workers = 4
timeout = 30

[server.ssl]
enabled = false
cert_file = "/path/to/cert.pem"
key_file = "/path/to/key.pem"

[database]
url = "mongodb://localhost:27017/treescribe"
max_connections = 10
timeout = 5000

[logging]
level = "info"
file = "treescribe.log"
rotate = true
max_size = "10MB"
format = "json"

[features]
yaml_parser = true
json_parser = true
markdown_parser = true
html_parser = true
xml_parser = true
javascript_parser = true
plugin_system = true

[performance]
cache_size = 100
parse_timeout = 5000
max_file_size = "50MB"
virtual_scroll = true

[[parsers]]
name = "YAML Parser"
format = "yaml"
extensions = ["yml", "yaml"]
priority = 1
config = { preserve_quotes = true, allow_duplicate_keys = false }

[[parsers]]
name = "JSON Parser"
format = "json"
extensions = ["json"]
priority = 1
config = { strict_mode = true, allow_comments = false }

[[parsers]]
name = "Markdown Parser"
format = "markdown"
extensions = ["md", "markdown", "mdown"]
priority = 2
config = { gfm = true, tables = true, breaks = false }

[[parsers]]
name = "HTML Parser"
format = "html"
extensions = ["html", "htm"]
priority = 2
config = { preserve_whitespace = false, extract_metadata = true }

[[parsers]]
name = "XML Parser"  
format = "xml"
extensions = ["xml", "svg"]
priority = 2
config = { namespace_aware = true, validate_schema = false }

[ui]
theme = "light"
font_family = "Monaco, 'Courier New', monospace"
font_size = 14
line_height = 1.5
show_line_numbers = true
highlight_current_line = true

[ui.colors.light]
background = "#ffffff"
foreground = "#333333"
accent = "#667eea"
border = "#e9ecef"

[ui.colors.dark]
background = "#1e1e1e"
foreground = "#d4d4d4"
accent = "#569cd6"
border = "#404040"

[keyboard]
expand_all = "Ctrl+E"
collapse_all = "Ctrl+Shift+E"
search = "Ctrl+F"
clear_search = "Escape"
next_result = "F3"
previous_result = "Shift+F3"

[export]
formats = ["html", "json", "yaml", "markdown"]
include_metadata = true
pretty_print = true
compress = false